# Stage 1: Build
FROM node:20 AS build

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .

ARG BACKEND_ENV
RUN echo "$BACKEND_ENV" > .env
RUN export $(grep -v '^#' .env | xargs) && npm run build

# Stage 2: Production
FROM node:20-slim

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/package*.json ./
RUN npm install --only=production

COPY --from=build /usr/src/app/dist ./dist

COPY --from=build /usr/src/app/.env .env

EXPOSE 3000

CMD ["node", "dist/main.js"]